In [20]:
import pandas as pd
import json

In [6]:
df = pd.read_csv("match_data.csv")
df

,id,team1,team2,winner,margin,ground,matchDate,scorecard
0,1,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,2,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,3,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,4,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,5,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
5,6,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
6,7,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
7,8,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
8,9,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
9,10,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
10,11,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
11,12,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
12,13,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
13,14,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
14,15,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
15,16,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
16,17,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
17,18,South Africa,Zimbabwe,no result,NaN,Hobart,"Oct 24, 2022",T20I # 1844
18,19,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
19,20,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
20,21,Afghanistan,New Zealand,abandoned,NaN,Melbourne,"Oct 26, 2022",T20I # 1846a
21,22,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
22,23,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
23,24,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
24,25,Afghanistan,Ireland,abandoned,NaN,Melbourne,"Oct 28, 2022",T20I # 1849a
25,26,Australia,England,abandoned,NaN,Melbourne,"Oct 28, 2022",T20I # 1849b
26,27,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
27,28,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
28,29,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
29,30,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
30,31,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
31,32,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
32,33,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
33,34,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
34,35,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
35,36,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
36,37,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
37,38,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
38,39,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
39,40,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
40,41,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
41,42,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
42,43,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
43,44,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
44,45,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879

In [10]:
new_df  = df.drop('id',axis=1)

In [11]:
new_df.shape

(45, 7)

In [18]:
new_df.rename(columns = {'scorecard':'match_id'}, inplace = True)

In [19]:
new_df.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [27]:
with open("t20_json_files/t20_wc_batting_summary.json") as f:
    data = json.load(f)
    all_rec =[]
    for rec in data:
        all_rec.extend(rec['battingSummary'])
# all_rec

df_batting = pd.DataFrame(all_rec)
df_batting

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
...,...,...,...,...,...,...,...,...,...,...
694,Pakistan Vs England,England,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,2,0,111.11
695,Pakistan Vs England,England,4,Ben Stokes,,52,49,5,1,106.12
696,Pakistan Vs England,England,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,1,0,86.95
697,Pakistan Vs England,England,6,Moeen Ali,b Mohammad Wasim,19,13,3,0,146.15
698,Pakistan Vs England,England,7,Liam Livingstone,,1,1,0,0,100.00

In [42]:
match_id_dict={}

for index,row in new_df.iterrows():
    key1 = row['team1'] + " Vs " +row['team2']
    key2 = row['team2'] + " Vs " +row['team1']   
    
    match_id_dict[key1] = row['match_id']
    match_id_dict[key2] = row['match_id']    

match_id_dict

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia': 'T20I # 1823',
 'Netherlands Vs U.A.E.': 'T20I # 1825',
 'U.A.E. Vs Netherlands': 'T20I # 1825',
 'Scotland Vs West Indies': 'T20I # 1826',
 'West Indies Vs Scotland': 'T20I # 1826',
 'Ireland Vs Zimbabwe': 'T20I # 1828',
 'Zimbabwe Vs Ireland': 'T20I # 1828',
 'Namibia Vs Netherlands': 'T20I # 1830',
 'Netherlands Vs Namibia': 'T20I # 1830',
 'Sri Lanka Vs U.A.E.': 'T20I # 1832',
 'U.A.E. Vs Sri Lanka': 'T20I # 1832',
 'Ireland Vs Scotland': 'T20I # 1833',
 'Scotland Vs Ireland': 'T20I # 1833',
 'West Indies Vs Zimbabwe': 'T20I # 1834',
 'Zimbabwe Vs West Indies': 'T20I # 1834',
 'Netherlands Vs Sri Lanka': 'T20I # 1835',
 'Sri Lanka Vs Netherlands': 'T20I # 1835',
 'Namibia Vs U.A.E.': 'T20I # 1836',
 'U.A.E. Vs Namibia': 'T20I # 1836',
 'Ireland Vs West Indies': 'T20I # 1837',
 'West Indies Vs Ireland': 'T20I # 1837',
 'Scotland Vs Zimbabwe': 'T20I # 1838',
 'Zimbabwe Vs Scotland': 'T20I # 1838',
 'Australia Vs New Zealand': 'T20I # 1839',
 'New Zealand Vs Australia': 'T20I # 1839',
 'Afghanistan Vs England': 'T20I # 1840',
 'England Vs Afghanistan': 'T20I # 1840',
 'Ireland Vs Sri Lanka': 'T20I # 1841',
 'Sri Lanka Vs Ireland': 'T20I # 1841',
 'India Vs Pakistan': 'T20I # 1842',
 'Pakistan Vs India': 'T20I # 1842',
 'Bangladesh Vs Netherlands': 'T20I # 1843',
 'Netherlands Vs Bangladesh': 'T20I # 1843',
 'South Africa Vs Zimbabwe': 'T20I # 1844',
 'Zimbabwe Vs South Africa': 'T20I # 1844',
 'Australia Vs Sri Lanka': 'T20I # 1845',
 'Sri Lanka Vs Australia': 'T20I # 1845',
 'England Vs Ireland': 'T20I # 1846',
 'Ireland Vs England': 'T20I # 1846',
 'Afghanistan Vs New Zealand': 'T20I # 1846a',
 'New Zealand Vs Afghanistan': 'T20I # 1846a',
 'Bangladesh Vs South Africa': 'T20I # 1847',
 'South Africa Vs Bangladesh': 'T20I # 1847',
 'India Vs Netherlands': 'T20I # 1848',
 'Netherlands Vs India': 'T20I # 1848',
 'Pakistan Vs Zimbabwe': 'T20I # 1849',
 'Zimbabwe Vs Pakistan': 'T20I # 1849',
 'Afghanistan Vs Ireland': 'T20I # 1849a',
 'Ireland Vs Afghanistan': 'T20I # 1849a',
 'Australia Vs England': 'T20I # 1849b',
 'England Vs Australia': 'T20I # 1849b',
 'New Zealand Vs Sri Lanka': 'T20I # 1850',
 'Sri Lanka Vs New Zealand': 'T20I # 1850',
 'Bangladesh Vs Zimbabwe': 'T20I # 1851',
 'Zimbabwe Vs Bangladesh': 'T20I # 1851',
 'Netherlands Vs Pakistan': 'T20I # 1852',
 'Pakistan Vs Netherlands': 'T20I # 1852',
 'India Vs South Africa': 'T20I # 1853',
 'South Africa Vs India': 'T20I # 1853',
 'Australia Vs Ireland': 'T20I # 1855',
 'Ireland Vs Australia': 'T20I # 1855',
 'Afghanistan Vs Sri Lanka': 'T20I # 1856',
 'Sri Lanka Vs Afghanistan': 'T20I # 1856',
 'England Vs New Zealand': 'T20I # 1858',
 'New Zealand Vs England': 'T20I # 1858',
 'Netherlands Vs Zimbabwe': 'T20I # 1859',
 'Zimbabwe Vs Netherlands': 'T20I # 1859',
 'Bangladesh Vs India': 'T20I # 1860',
 'India Vs Bangladesh': 'T20I # 1860',
 'Pakistan Vs South Africa': 'T20I # 1861',
 'South Africa Vs Pakistan': 'T20I # 1861',
 'Ireland Vs New Zealand': 'T20I # 1862',
 'New Zealand Vs Ireland': 'T20I # 1862',
 'Australia Vs Afghanistan': 'T20I # 1864',
 'Afghanistan Vs Australia': 'T20I # 1864',
 'England Vs Sri Lanka': 'T20I # 1867',
 'Sri Lanka Vs England': 'T20I # 1867',
 'Netherlands Vs South Africa': 'T20I # 1871',
 'South Africa Vs Netherlands': 'T20I # 1871',
 'Bangladesh Vs Pakistan': 'T20I # 1872',
 'Pakistan Vs Bangladesh': 'T20I # 1872',
 'India Vs Zimbabwe': 'T20I # 1873',
 'Zimbabwe Vs India': 'T20I # 1873',
 'New Zealand Vs Pakistan': 'T20I # 1877',
 'Pakistan Vs New Zealand': 'T20I # 1877',
 'England Vs India': 'T20I # 1878',
 'India Vs England': 'T20I # 1878',
 'England Vs Pakistan': 'T20I # 1879',
 'Pakistan Vs England': 'T20I # 1879'}

In [28]:
df_batting["out/not_out"] = df_batting["dismissal"].apply(lambda x: "out" if len(x)>0 else "not_out")

In [30]:
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09,out

In [31]:
df_batting.drop("dismissal",axis= 1,inplace=True)

In [33]:
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out

In [35]:
df_batting["batsmanName"]=df_batting["batsmanName"].apply(lambda x: x.replace("â€",""))
df_batting["batsmanName"]=df_batting["batsmanName"].apply(lambda x: x.replace("\xa0",""))

In [37]:
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out

In [43]:
df_batting['match_id'] = df_batting["match"].map(match_id_dict)

In [46]:
df_batting.head(50)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out,T20I # 1823
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out,T20I # 1823
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out,T20I # 1823
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out,T20I # 1823
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out,T20I # 1823
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out,T20I # 1823
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out,T20I # 1823
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out,T20I # 1823
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out,T20I # 1823
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out,T20I # 1823
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out,T20I # 1823
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,out,T20I # 1823
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,out,T20I # 1823
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,out,T20I # 1823
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,not_out,T20I # 1823
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,out,T20I # 1825
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,out,T20I # 1825
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,out,T20I # 1825
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,18,21,0,0,85.71,out,T20I # 1825
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,out,T20I # 1825
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,out,T20I # 1825
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),1,2,0,0,50.00,out,T20I # 1825
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,out,T20I # 1825
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,not_out,T20I # 1825
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,not_out,T20I # 1825
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,out,T20I # 1825
30,U.A.E. Vs Netherlands,Netherlands,2,Max O'Dowd,23,18,3,1,127.77,out,T20I # 1825
31,U.A.E. Vs Netherlands,Netherlands,3,Bas de Leede,14,18,1,0,77.77,out,T20I # 1825
32,U.A.E. Vs Netherlands,Netherlands,4,Colin Ackermann,17,19,1,0,89.47,out,T20I # 1825
33,U.A.E. Vs Netherlands,Netherlands,5,Tom Cooper,8,16,0,0,50.00,out,T20I # 1825
34,U.A.E. Vs Netherlands,Netherlands,6,Scott Edwards(c),16,19,0,0,84.21,not_out,T20I # 1825
35,U.A.E. Vs Netherlands,Netherlands,7,Roelof van der Merwe,0,2,0,0,0.00,out,T20I # 1825
36,U.A.E. Vs Netherlands,Netherlands,8,Tim Pringle,15,16,0,0,93.75,out,T20I # 1825
37,U.A.E. Vs Netherlands,Netherlands,9,Logan van Beek,4,4,0,0,100.00,not_out,T20I # 1825
38,Scotland Vs West Indies,Scotland,1,George Munsey,66,53,9,0,124.52,not_out,T20I # 1826
39,Scotland Vs West Indies,Scotland,2,Michael Jones,20,17,3,0,117.64,out,T20I # 1826
40,Scotland Vs West Indies,Scotland,3,Matthew Cross,3,5,0,0,60.00,out,T20I # 1826
41,Scotland Vs West Indies,Scotland,4,Richie Berrington(c),16,14,0,1,114.28,out,T20I # 1826
42,Scotland Vs West Indies,Scotland,5,Calum MacLeod,23,14,4,0,164.28,out,T20I # 1826
43,Scotland Vs West Indies,Scotland,6,Michael Leask,4,6,0,0,66.66,out,T20I # 1826
44,Scotland Vs West Indies,Scotland,7,Chris Greaves,16,11,2,0,145.45,not_out,T20I # 1826
45,Scotland Vs West Indies,West Indies,1,Kyle Mayers,20,13,3,1,153.84,out,T20I # 1826
46,Scotland Vs West Indies,West Indies,2,Evin Lewis,14,13,1,1,107.69,out,T20I # 1826
47,Scotland Vs West Indies,West Indies,3,Brandon King,17,15,3,0,113.33,out,T20I # 1826
48,Scotland Vs West Indies,West Indies,4,Nicholas Pooran(c),5,9,0,0,55.55,out,T20I # 1826
49,Scotland Vs West Indies,West Indies,5,Shamarh Brooks,4,9,0,0,44.44,out,T20I # 1826

In [47]:
df_batting.to_csv("t20_csv_files/fact_bating_summary.csv",index = False)

In [48]:
with open('t20_json_files/t20_wc_bowling_summary.json') as f:
    data = json.load(f)
    all_records = []
    for rec in data:
        all_records.extend(rec['bowlingSummary'])
all_records[:2]

[{'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Maheesh Theekshana',
  'overs': '4',
  'maiden': '0',
  'runs': '23',
  'wickets': '1',
  'economy': '5.75',
  '0s': '7',
  '4s': '0',
  '6s': '0',
  'wides': '2',
  'noBalls': '0'},
 {'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Dushmantha Chameera',
  'overs': '4',
  'maiden': '0',
  'runs': '39',
  'wickets': '1',
  'economy': '9.75',
  '0s': '6',
  '4s': '3',
  '6s': '1',
  'wides': '2',
  'noBalls': '0'}]

In [49]:
df_bowling = pd.DataFrame(all_records)
print(df_bowling.shape)
df_bowling.head()

(500, 13)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0

In [51]:
df_bowling['match_id'] = df_bowling['match'].map(match_id_dict)
df_bowling.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823

In [52]:
df_bowling.to_csv('t20_csv_files/fact_bowling_summary.csv', index = False)

In [53]:
with open('t20_json_files/t20_wc_player_info.json') as f:
    data = json.load(f)

In [56]:
df_players = pd.DataFrame(data)

print(df_players.shape)
df_players.head()

(219, 6)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
...,...,...,...,...,...,...
145,Nurul Hasanâ€,Bangladesh,Right hand Bat,,Wicketkeeper Batter,"Nurul Hasan, who made his first-class debut in..."
146,Mosaddek Hossain,Bangladesh,Right hand Bat,Right arm Offbreak,Middle order Batter,"Mosaddek Hossain, who comes from a family of c..."
147,Taskin Ahmed,Bangladesh,Left hand Bat,Right arm Fast,Bowler,Even before he was anywhere near making his in...
148,Hasan Mahmud,Bangladesh,Right hand Bat,Right arm Medium,Bowler,Hasan Mahmud is one among a group of young pac...
149,Shariz Ahmad,Netherlands,Left hand Bat,Legbreak Googly,Bowler,

In [59]:
df_players['name'] = df_players['name'].apply(lambda x: x.replace('â€', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('†', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('\xa0', ''))
df_players.tail(50)

,name,team,battingStyle,bowlingStyle,playingRole,description
169,Lungi Ngidi,South Africa,Right hand Bat,Right arm Fast medium,Bowler,"A tall, imposing paceman, Lungi Ngidi can reac..."
170,Keshav Maharaj,South Africa,Right hand Bat,Slow Left arm Orthodox,Bowler,"A left-arm spinner from Northwood Boys High, t..."
171,Anrich Nortje,South Africa,Right hand Bat,Right arm Fast,Bowler,Anrich Nortje is a genuine quick who has been ...
172,Timm van der Gugten,Netherlands,Right hand Bat,Right arm Fast medium,Bowler,"Timm van der Gugten, born in Sydney, made his ..."
173,Finn Allen,New Zealand,Right hand Bat,,Top order Batter,
174,Devon Conway,New Zealand,Left hand Bat,Right arm Medium,Wicketkeeper Batter,
175,Kane Williamson(c),New Zealand,Right hand Bat,Right arm Offbreak,Top order Batter,By the time Kane Williamson is finished with p...
176,Glenn Phillips,New Zealand,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Glenn Phillips is a top-order wicketkeeper-bat...
177,James Neesham,New Zealand,Left hand Bat,Right arm Medium fast,Batting Allrounder,"Allrounder, and Twitter star, Jimmy Neesham we..."
178,Tim David,Australia,Right hand Bat,Right arm Offbreak,Middle order Batter,Mumbai Indians' decision to sign Tim David for...
179,Matthew Wade,Australia,Left hand Bat,Right arm Medium,Wicketkeeper Batter,It has been a career of reinvention for Matthe...
180,Adam Zampa,Australia,Right hand Bat,Legbreak Googly,Bowler,"An energetic and competitive legspinner, Adam ..."
181,Trent Boult,New Zealand,Right hand Bat,Left arm Fast medium,Bowler,Rated as one half of the best new-ball pair in...
182,Tim Southee,New Zealand,Right hand Bat,Right arm Medium fast,Bowler,"Tim Southee, a right-arm swing bowler, burst u..."
183,Mitchell Santner,New Zealand,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,"A left-handed batsman and left-arm spinner, Mi..."
184,Lockie Ferguson,New Zealand,Right hand Bat,Right arm Fast,Bowler,"A right-arm quick with a good bouncer, it is L..."
185,Ish Sodhi,New Zealand,Right hand Bat,Legbreak,Bowler,There is little in Ish Sodhi's statistics to s...
186,Aryan Lakra,U.A.E.,Left hand Bat,Slow Left arm Orthodox,Bowler,
187,Stephan Myburgh,Netherlands,Left hand Bat,Right arm Offbreak,Opening Batter,
188,Brandon Glover,Netherlands,Right hand Bat,Right arm Fast,Bowler,"A Dutch-South African fast bowler, Brandon Glo..."
189,Shoriful Islam,Bangladesh,Left hand Bat,Left arm Medium fast,Bowler,"At 6ft three inches, Shoriful Islam became a l..."
190,Daryl Mitchell,New Zealand,Right hand Bat,Right arm Medium,Allrounder,Daryl Mitchell was called into New Zealand's T...
191,Kasun Rajitha,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,"Virtually unheard of before 2015, the first in..."
192,Deepak Hooda,India,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."
193,Rilee Rossouw,South Africa,Left hand Bat,Right arm Offbreak,Top order Batter,A stylish top-order player with an elegant and...
194,Aiden Markram,South Africa,Right hand Bat,Right arm Offbreak,Opening Batter,The first South Africa captain to win a World ...
195,David Miller,South Africa,Left hand Bat,Right arm Offbreak,Middle order Batter,A hard-hitting left-hander with a penchant for...
196,Tristan Stubbs,South Africa,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,
197,Nasum Ahmed,Bangladesh,Left hand Bat,Slow Left arm Orthodox,Bowler,
198,Mohammad Haris,Pakistan,Right hand Bat,Right arm Offbreak,Middle order Batter,
199,Mohammad Wasim,Pakistan,Right hand Bat,Right arm Fast medium,Allrounder,
200,Ebadot Hossain,Bangladesh,Right hand Bat,Right arm Fast medium,Bowler,Ebadat Hossain Chowdhury's journey from being ...
201,Heinrich Klaasen,South Africa,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A clean-hitting, wicketkeeper batsman, Heinric..."
202,Brad Evans,Zimbabwe,Right hand Bat,Right arm Fast,Allrounder,
203,Fakhar Zaman,Pakistan,Left hand Bat,Slow Left arm Orthodox,Opening Batter,"Born in Mardan, where the standard of batsmans..."
204,Cameron Green,Australia,Right hand Bat,Right arm Fast medium,Batting Allrounder,Contracted to Western Australia as a schoolboy...
205,Steven Smith,Australia,Right hand Bat,Legbreak Googly,Middle order Batter,"In a career of twists and turns, Steven Smith ..."
206,Matthew Wade(c),Australia,Left hand Bat,Right arm Medium,Wicketkeeper Batter,It has been a career of reinvention for Matthe...
207,Kane Richardson,Australia,Right hand Bat,Right arm Fast medium,Bowler,A pace bowler who has often been on the fringe...
208,Gulbadin Naib,Afghanistan,Right hand Bat,Right arm Medium fast,Batting Allrounder,Gulbadin Naib's first love in the sporting wor...
209,Darwish Rasooli,Afghanistan,Right hand Bat,Right arm Offbreak,Top order Batter,
210,Naveen-ul-Haq,Afghanistan,Right hand Bat,Right arm Medium fast,Bowler,
211,Rishabh Pant,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."
212,Tony Munyonga,Zimbabwe,Right hand Bat,Right arm Offbreak,Allrounder,
213,Wellington Masakadza,Zimbabwe,Left hand Bat,Slow Left arm Orthodox,Bowler,
214,Tabraiz Shamsi,South Africa,Right hand Bat,Left arm Wrist spin,Bowler,A left-arm wristspin bowler with ample variati...
215,Phil Salt,England,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Phil Salt's fearless ball-striking at the top ...
216,Chris Jordan,England,Right hand Bat,Right arm Fast medium,Bowler,"Chris Jordan, a fast bowler with a level-heade..."
217,Regis Chakabva(c),Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."
218,Mehidy Hasan Miraz,Bangladesh,Right hand Bat,Right arm Offbreak,Allrounder,Mehedi Hasan Miraz has emerged as one of the b...

In [60]:
df_players[df_players['team'] == 'India']

,name,team,battingStyle,bowlingStyle,playingRole,description
127,KL Rahul,India,Right hand Bat,,Opening Batter,"A tall, elegant right-hand batsman who can kee..."
128,Rohit Sharma(c),India,Right hand Bat,Right arm Offbreak,Top order Batter,"Languid and easy on the eye, Rohit Sharma owne..."
129,Virat Kohli,India,Right hand Bat,Right arm Medium,Top order Batter,India has given to the world many a great cric...
130,Suryakumar Yadav,India,Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter,Hard-hitting 360-degree batter Suryakumar Yada...
131,Axar Patel,India,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,Left-arm spinner Axar Patel has been increasin...
132,Hardik Pandya,India,Right hand Bat,Right arm Medium fast,Allrounder,Hardik Pandya swears by living life king size ...
133,Dinesh Karthik,India,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Not many would forget the sight of Dinesh Kart...
134,Ravichandran Ashwin,India,Right hand Bat,Right arm Offbreak,Bowling Allrounder,R Ashwin took the tricks and skills he learned...
135,Bhuvneshwar Kumar,India,Right hand Bat,Right arm Medium,Bowler,"At the time of his India debut in 2012, Bhuvne..."
136,Arshdeep Singh,India,Left hand Bat,Left arm Medium fast,Bowler,
137,Mohammed Shami,India,Right hand Bat,Right arm Fast,Bowler,Mohammed Shami was India's leading fast bowler...
192,Deepak Hooda,India,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."
211,Rishabh Pant,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."

In [61]:
df_players.to_csv('t20_csv_files/dim_players_no_images.csv', index = False)